### PR TITLE
Token based auth

### PR DESCRIPTION
**Pull request by Integral**
Hey!

Sorry for the delay.
This is very basic rewrite of user api.
You can register, login and use token.

When you're login you'll receive json with token property. Use it inside `Authorization` header like this:
`Bearer your_token_here`
second part of token is base64 encoded user data

There are a lot of things to change. I don't like all of this json responses with success boolean inside. We should use http statuses for this...

### CODE REVIEW

**Comment by Integral** [comment]
And don't forget to do `npm install` and `npm run seed`

**Comment by Integral** [comment]
@michael, could you review this?

**Comment by michael** [comment]
I will integrate this today. Thanks a lot! :)

**Comment by michael** [comment]
Hey maybe we should introduce a username also. I just thought it would be nice to be able to browse the journal by author.. and that we could do by username. 

http://myjournal.com/john

Also since we use users only in the backend and not for front end commenting we could add columns for author bio, location and website.. and a profile image.

What do you think?

**Comment by Integral** [comment]
Hey! :)

We can send any user info as [data property](https://github.com/data4society/journal/blob/master/server/api/user.js#L49). It will be available in data json object. Actually it was your idea :)

Regarding username - we should place it outside of a data object if we want to give ability to use it during authorisation instead of an email.

**Comment by michael** [comment]
So the data property is just there to store whatever i want? i can also leave it blank?

I'm about to create one default user, in the initial seed.

**Comment by Integral** [comment]
yeah!

**Pull request merged**
